Scribe v0.7.1
* Check for error when downloading zipfile
* Add moving .conf-opkg files to examples
* only copy skynet to syslog-ng.d if it doesn't already exist
* change flow for updating
* add a function for updating filters
* fix redaction of usernames in debug output when name is longer than 8 chars

#TODO: check for existence of fiiles when copying to .d and examples directories

diff --git a/scribe b/scribe
--- a/scribe
+++ b/scribe
@@ -30,8 +30,8 @@ action=$1
 got_zip="no"
 [ -z "$TMP" ] && TMP=/opt/tmp
 
-readonly scribe_ver="v0.7_0 (Beta)"
-readonly scribe_branch="master"
+readonly scribe_ver="v0.7_1 (Beta)"
+readonly scribe_branch="gamma"
 readonly scribe_name="scribe"
 readonly scribe_author="cynicastic"
 readonly scribe_repo="https://raw.githubusercontent.com/$scribe_author/$scribe_name/$scribe_branch/$scribe_name"
@@ -115,15 +115,40 @@ getzip(){
     if [ "$got_zip" = "no" ]
     then
         dlt "$scribe_dir"
-        curl -fL https://github.com/$scribe_author/$scribe_name/archive/$scribe_branch.zip -o $TMP/$scribe_name.zip
-        unzip $TMP/$scribe_name.zip -d $TMP
-        opkg update
-        got_zip="yes"
+        if curl -fL https://github.com/$scribe_author/$scribe_name/archive/$scribe_branch.zip -o $TMP/$scribe_name.zip
+        then
+            unzip $TMP/$scribe_name.zip -d $TMP
+            opkg update
+            got_zip="yes"
+        else
+            printf "\n$white %s GitHub repository$red is unavailable! $std -- Aborting.\n" "$scribe_name"
+            exit 1
+        fi
+    fi
+}
+
+# setup example files in /usr/share/$1/examples
+# install default file in /usr/etc/$1.d
+setup_expl(){
+    [ "$1" = "$sng" ] && d_dir="$syslogng_d" && share="$syslogng_share" && conf="$syslogng_conf"
+    [ "$1" = "$lr"  ] && d_dir="$logrotate_d" && share="$logrotate_share" && conf="$logrotate_conf"
+    cp -pu "$scribe_dir/$1.d/*" $d_dir/
+    [ ! -d $share ] && mkdir $share
+    [ ! -d $share/examples ] && mkdir $share/examples
+    cp -pf "$scribe_dir/$1.share/*" $share/examples/
+
+    if [ -e "/opt/etc/$1.conf-opkg" ]
+    then
+        cp -pf "/opt/etc/$1.conf-opkg" $share/examples
+        dlt "/opt/etc/$1.conf-opkg"
+    elif [ ! -e "$share/examples/$1.conf-opkg" ]
+    then
+        cp -pf $conf "$share/examples/$1.conf-opkg"
     fi
 }
 
 force_install(){
-    printf "\n$white $u_l""$1""$std$white already installed!\n"
+    printf "\n$white $u_l$1$std$white already installed!\n"
     [ "$1" != "$scribe_name" ] && printf "$yellow Forcing installation may overwrite modified configuration files!\n"
     printf "$white Do you want to force re-installation of $1 [y|n]? $std"
     read -r reinstall
@@ -146,16 +171,6 @@ install(){
 #### install sub-functions ####
 ###############################
 
-# setup example files in /usr/share
-    setup_exp(){
-        [ "$1" = "$sng" ] && d_dir="$syslogng_d" && share="$syslogng_share"
-        [ "$1" = "$lr"  ] && d_dir="$logrotate_d" && share="$logrotate_share"
-        cp -pu "$scribe_dir"/"$1".d/* $d_dir/
-        [ ! -d $share ] && mkdir $share
-        [ ! -d $share/examples ] && mkdir $share/examples
-        cp -pu "$scribe_dir"/"$1".share/* $share/examples/
-    }
-
 # determine syslog-ng conf file version
     sng_conf_ver(){ grep '@version:' $syslogng_conf | awk '{ printf( $2 ); }' | awk -F. '{ printf ("%d%03d", $1, $2); }'; }
 
@@ -169,13 +184,12 @@ install(){
 # setup syslog-ng
     setup_sng(){
         printf "$white setting up syslog-ng ..."
-        cp -pf $syslogng_conf $syslogng_share/examples/$sng.conf-pkg
         cp -pu "$scribe_dir"/init.d/rc.func.syslog-ng $init_d/
         chmod u=rw,go=r $init_d/rc.func.syslog-ng
         sed -i '/rc.func.syslog-ng/d; \~/opt/etc/init.d/rc.func~i . /opt/etc/init.d/rc.func.syslog-ng # added by scribe\n' $S01sng_loc
         finis
         printf "\n$white Do you wish to install smaller syslog-ng.conf? [RECOMMENDED]\n"
-        printf "$std (default %s.conf is backed up to %s/%s.conf-pkg)" "$sng" "$syslogng_share" "$sng"
+        printf "$std (default %s.conf is backed up to %s/%s.conf-opkg)" "$sng" "$syslogng_share" "$sng"
         printf "$white [y|n]? "
         read -r use_small
         case "$use_small" in
@@ -192,7 +206,7 @@ install(){
 
 # setup logrotate
     setup_lr(){
-    # assumes since entware is required / installed, post-mount exists and is properly executable
+        # assumes since entware is required / installed, post-mount exists and is properly executable
         printf "$blue adding logrotate cron job$white ..."
         sed -i '/cru a logrotate/d' $postmount
         # respect user's logrotate cron job if it exists
@@ -210,7 +224,7 @@ install(){
 
     printf "$white setting up $1 ..."
     opkg install $force "$1" 
-    setup_exp "$1"
+    setup_expl "$1"
     [ "$1" = "$sng" ] && setup_sng
     [ "$1" = "$lr"  ] && setup_lr
 }
@@ -218,15 +232,18 @@ install(){
 
 setup_scribe(){
     printf "$white setting up %s ..." "$scribe_name"
-    cp -pf "$scribe_dir"/"$scribe_name" "$scribe_script"
+    cp -pf "$scribe_dir/$scribe_name" "$scribe_script"
     chmod 0755 $scribe_script
     [ ! -e "/opt/bin/$scribe_name" ] && ln -s $scribe_script /opt/bin
     if [ "$skynet_installed" = "yes" ]
     then
-        mv $syslogng_share/examples/skynet $syslogng_d 
-        printf "$blue setting skynet log file location$white ..."
-        skynetlog=$( grep 'file("' $syslogng_d/skynet | awk -F\" '{ printf ( $2 ); }'; )
-        sh /jffs/scripts/firewall settings syslog "$skynetlog" > /dev/null 2>&1
+        if [ ! -e "$syslogng_d/skynet" ]
+        then
+            cp -pu $syslogng_share/examples/skynet $syslogng_d 
+            printf "$blue setting skynet log file location$white ..."
+            skynetlog=$( grep 'file("' $syslogng_d/skynet | awk -F\" '{ printf ( $2 ); }'; )
+            sh /jffs/scripts/firewall settings syslog "$skynetlog" > /dev/null 2>&1
+        fi
     else
         printf "$red Skynet NOT installed$white ..."
     fi
@@ -320,22 +337,16 @@ menu_update(){
         printf "\n$white New version available!\n"
         printf " Do you wish to upgrade [y|n] $std"
     else
-        printf "\n$white No new version available.\n"
+        [ "$installed_ver" -eq "$github_ver" ] && ver_status="(GitHub version equal to local)" || ver_status="(GitHub version LESS THAN local!)"
+        printf "\n$white No new version available.  %s\n" "$ver_status"
         printf " Do you wish to force re-installation of scribe script? [y|n] $std"
     fi
     
     read -r instl
     case "$instl" in
         [yY][eE][sS]|[yY])
-            if curl -fL --retry 3 "$scribe_repo" -o $scribe_script
-            then
-                chmod 0755 $scribe_script
-                [ ! -e "/opt/bin/$scribe_name" ] && ln -s $scribe_script /opt/bin
-                printf "\n$white $scribe_name successfully updated.$std\n"
-            else
-                printf "\n$white $scribe_name$red FAILED$white to update!$std\n"
-                return 1
-            fi
+            getzip
+            setup_scribe
             ;;
         *)
             printf "\n$white $scribe_name not updated!$std\n"
@@ -343,12 +354,18 @@ menu_update(){
     esac
 }
 
+menu_filters(){
+    getzip
+    setup_expl "$sng"
+    setup_expl "$lr"
+}
+
 gather_debug(){
     scribe_debug_name=$scribe_name"_debug.log"
     scribe_debug=$TMP/$scribe_debug_name
     [ -z "$(nvram get odmpid)" ] && model="$(nvram get productid)" || model="$(nvram get odmpid)"
     printf "\n$white gathering debugging information ..."
-    printf "### Scribe Version: %s\n" $scribe_ver > $scribe_debug
+    printf "### Scribe Version: %s\n" "$scribe_ver" > $scribe_debug
 
     # everything between { } goes to $scribe_debug
     {
@@ -364,6 +381,8 @@ gather_debug(){
         ls -ld /jffs/syslog*
         printf "\n### top output:\n"
         top -b -n1 | head
+        printf "\n### syslog references in top:\n"
+        top -b -n1 | grep syslog
         printf "\n### init.d directory:\n"
         ls -l /opt/etc/init.d
         printf "\n### contents of S01syslog-ng\n"
@@ -402,14 +421,15 @@ gather_debug(){
     fi
 
     printf "\n### end of output ###\n" >> $scribe_debug
-    sed -i "s/$USER/[redacted]/g" "$scribe_debug"
+    redact=$(echo "$USER" | awk  '{ string=substr($0, 1, 8); print string; }' )
+    sed -i "s/$redact/redacted/g" "$scribe_debug"
     printf " taring the output ..."
     tar -zcvf $scribe_debug.tar.gz -C $TMP $scribe_debug_name > /dev/null 2>&1
     finis
 
-    printf " Debug output stored in %s, please review this file\n" $scribe_debug
+    printf " Debug output stored in %s, please review this file\n" "$scribe_debug"
     printf " to ensure you understand what information is being disclosed.\n\n"
-    printf " Tarball of debug output is %s.tar.gz, \n" $scribe_debug
+    printf " Tarball of debug output is %s.tar.gz \n" "$scribe_debug"
 }
 
 scribe_menu(){
@@ -500,6 +520,11 @@ case $action in
         get_vers
         prt_vers
         menu_update
+        ;;
+
+# update syslog-ng and logrotate filters
+    update-filters | filters)
+        menu_filters
         ;;
 
 # show total combined config
