Update scribe
harmonize variable names

diff --git a/scribe b/scribe
--- a/scribe
+++ b/scribe
@@ -61,22 +61,22 @@ readonly arch="$( uname -m )"
 
 # miscellaneous constants
 readonly sng="syslog-ng"
-readonly sngreqd="3.19"
+readonly sng_reqd="3.19"
 readonly lr="logrotate"
 readonly init_d="/opt/etc/init.d"
-readonly S01sng_loc="$init_d/S01$sng"
+readonly S01sng_init="$init_d/S01$sng"
 readonly rcfunc_sng="rc.func.$sng"
 readonly rcfunc_loc="$init_d/$rcfunc_sng"
-readonly syslogng_loc="/opt/sbin/$sng"
-readonly logrotate_loc="/opt/sbin/$lr"
-readonly syslogng_conf="/opt/etc/$sng.conf"
+readonly sng_loc="/opt/sbin/$sng"
+readonly lr_loc="/opt/sbin/$lr"
+readonly sng_conf="/opt/etc/$sng.conf"
 readonly sngconf_merged="$TMP/syslog-ng-complete.conf"
-readonly logrotate_conf="/opt/etc/$lr.conf"
+readonly lr_conf="/opt/etc/$lr.conf"
 readonly lr_daily="/opt/tmp/logrotate.daily"
-readonly syslogng_d="/opt/etc/$sng.d"
-readonly logrotate_d="/opt/etc/$lr.d"
-readonly syslogng_share="/opt/share/$sng"
-readonly logrotate_share="/opt/share/$lr"
+readonly sngd_d="/opt/etc/$sng.d"
+readonly lrd_d="/opt/etc/$lr.d"
+readonly sng_share="/opt/share/$sng"
+readonly lr_share="/opt/share/$lr"
 readonly srvc_event="$script_d/service-event"
 readonly postmount="$script_d/post-mount"
 readonly divers="/opt/bin/diversion"
@@ -167,10 +167,10 @@ get_zip(){
 }
 
 sed_sng(){
-    printf "\n$white %34s" "checking $( basename $S01sng_loc ) ..."
-    if ! grep -q $rcfunc_sng $S01sng_loc
+    printf "\n$white %34s" "checking $( basename $S01sng_init ) ..."
+    if ! grep -q $rcfunc_sng $S01sng_init
     then
-        sed -i "\~/opt/etc/init.d/rc.func~i . $rcfunc_loc # added by scribe\n" $S01sng_loc
+        sed -i "\~/opt/etc/init.d/rc.func~i . $rcfunc_loc # added by scribe\n" $S01sng_init
         updated
     else
         present
@@ -203,7 +203,7 @@ lr_cron(){
     printf "\n$white %34s" "checking $( basename $postmount ) ..."
     if ! grep -q $lr $postmount
     then
-        echo "cru a $lr "'"5 0 * * *'" $logrotate_loc $logrotate_conf >> $lr_daily "'2>&1" # added by scribe' >> $postmount
+        echo "cru a $lr "'"5 0 * * *'" $lr_loc $lr_conf >> $lr_daily "'2>&1" # added by scribe' >> $postmount
         updated
     else
         present
@@ -212,7 +212,7 @@ lr_cron(){
 	printf "\n$white %34s" "checking $lr cron job ..."
     if ! cru l | grep -q $lr
     then
-        cru a $lr "5 0 * * * $logrotate_loc $logrotate_conf >> $lr_daily 2>&1"
+        cru a $lr "5 0 * * * $lr_loc $lr_conf >> $lr_daily 2>&1"
         updated
     else
         present
@@ -240,8 +240,8 @@ check_sng(){
 # install default file in /usr/etc/$1.d
 # all files in examples and .d must be 644 or 600
 setup_exmpls(){
-    [ "$1" = "$sng" ] && d_dir="$syslogng_d" && share="$syslogng_share" && conf="$syslogng_conf"
-    [ "$1" = "$lr"  ] && d_dir="$logrotate_d" && share="$logrotate_share" && conf="$logrotate_conf"
+    [ "$1" = "$sng" ] && d_dir="$sngd_d" && share="$sng_share" && conf="$sng_conf"
+    [ "$1" = "$lr"  ] && d_dir="$lrd_d" && share="$lr_share" && conf="$lr_conf"
     opkg="$1.conf-opkg"
     conf_opkg="$conf-opkg"
 
@@ -273,9 +273,9 @@ force_install(){
 }
 
 show_config(){
-    if [ -e $syslogng_loc ]
+    if [ -e $sng_loc ]
     then
-        $syslogng_loc --preprocess-into=$sngconf_merged && less $sngconf_merged
+        $sng_loc --preprocess-into=$sngconf_merged && less $sngconf_merged
         true
     else
         not_installed $sng
@@ -286,7 +286,7 @@ show_config(){
 run_logrotate(){
     dlt $lr_daily
     printf "\n$white %34s" "running $lr ..."
-    $logrotate_loc $logrotate_conf >> $lr_daily 2>&1
+    $lr_loc $lr_conf >> $lr_daily 2>&1
     finis
     printf "\n$magenta checking %s log for errors $cyan\n\n" "$lr"
     tail -v $lr_daily
@@ -344,11 +344,11 @@ menu_status(){
 install(){
 
 # determine syslog-ng conf file version
-    sng_conf(){
-        sngvers="$( grep -m1 '@version:' $syslogng_conf | awk '{ printf( $2 ); }'; )"
-        if [ "$( ver_num "$sngvers" )" -lt "$( ver_num "$sngreqd" )" ]
+    sng_ver_chk(){
+        sng_vers="$( grep -m1 '@version:' $sng_conf | awk '{ printf( $2 ); }'; )"
+        if [ "$( ver_num "$sng_vers" )" -lt "$( ver_num "$sng_reqd" )" ]
         then
-            printf "\n$red %s version %s or higher required!\n" "$sng" "$sngreqd"
+            printf "\n$red %s version %s or higher required!\n" "$sng" "$sng_reqd"
             printf "Please update your Entware packages and run scribe install again.$cyan\n\n"
             opkg remove "$sng"
             printf "$std\n\n"
@@ -362,16 +362,16 @@ install(){
         copy_rcfunc
         sed_sng
 
-        if [ "$( md5_file "$syslogng_share/examples/$sng.conf-scribe" )" != "$( md5_file "$syslogng_conf" )" ]
+        if [ "$( md5_file "$sng_share/examples/$sng.conf-scribe" )" != "$( md5_file "$sng_conf" )" ]
         then
-            printf "\n$white backing up %s to %s ...$std" "$syslogng_conf" "$syslogng_conf-prev"
-            cp -pf $syslogng_conf $syslogng_conf-prev
-            cp -pf $syslogng_share/examples/$sng.conf-scribe $syslogng_conf
+            printf "\n$white backing up %s to %s ...$std" "$sng_conf" "$sng_conf-prev"
+            cp -pf $sng_conf $sng_conf-prev
+            cp -pf $sng_share/examples/$sng.conf-scribe $sng_conf
             finis
             printf "\n$white NOTE: The syslog-ng.conf file provided by the Entware syslog-ng package sources a very\n"
             printf " complex set of logging functions most users don't need.$blue A replacement syslog-ng.conf has been\n"
-            printf " installed$white at %s that corrects this issue. The syslog-ng.conf file provided\n" "$syslogng_conf"
-            printf " by the Entware package has been moved to $blue%s$white.\n" "$syslogng_share/examples/$sng.conf-opkg"
+            printf " installed$white at %s that corrects this issue. The syslog-ng.conf file provided\n" "$sng_conf"
+            printf " by the Entware package has been moved to $blue%s$white.\n" "$sng_share/examples/$sng.conf-opkg"
             printf "\n %34s" "$sng installation ..."
         fi
         finis
@@ -389,7 +389,7 @@ install(){
     [ "X$2" = "XFORCE" ] && force="--force-reinstall"
     printf "\n$cyan"
     opkg install $force "$1" 
-    [ "$1" = "$sng" ] && sng_conf
+    [ "$1" = "$sng" ] && sng_ver_chk
     setup_exmpls "$1"
     [ "$1" = "$sng" ] && setup_sng
     [ "$1" = "$lr"  ] && setup_lr
@@ -402,11 +402,11 @@ setup_scribe(){
     [ ! -e "/opt/bin/$scribe_name" ] && ln -s $scribe_script /opt/bin
     if $skynet_inst
     then
-        if [ ! -e "$syslogng_d/skynet" ]
+        if [ ! -e "$sngd_d/skynet" ]
         then
-            cp -pu $syslogng_share/examples/skynet $syslogng_d 
+            cp -pu $sng_share/examples/skynet $sngd_d 
             printf "$blue setting skynet log file location$white ..."
-            skynetlog="$( grep -m1 'file("' $syslogng_d/skynet | awk -F\" '{ printf ( $2 ); }'; )"
+            skynetlog="$( grep -m1 'file("' $sngd_d/skynet | awk -F\" '{ printf ( $2 ); }'; )"
             sh $script_d/firewall settings syslog "$skynetlog" > /dev/null 2>&1
         fi
     fi
@@ -470,18 +470,18 @@ pre_install(){
 }
 
 menu_install(){
-        if [ ! -e $syslogng_loc ]
+        if [ ! -e $sng_loc ]
         then
             install "$sng"
         elif force_install "$sng"
         then
-            $S01sng_loc stop
+            $S01sng_init stop
             install "$sng" "FORCE"
         fi
         echo
-        $S01sng_loc start
+        $S01sng_init start
 
-        if [ ! -e $logrotate_loc ]
+        if [ ! -e $lr_loc ]
         then
             install "$lr"
         elif force_install "$lr"
@@ -506,31 +506,31 @@ menu_restart(){
     if check_sng
     then
         printf "$yellow Restarting %s... $std\n" "$sng"
-        $S01sng_loc restart
+        $S01sng_init restart
     else
         printf "$white %s$red NOT$white running! $yellow Starting %s ... $std\n" "$sng"
-        $S01sng_loc start
+        $S01sng_init start
     fi
 }
 
 uninstall(){
     echo
-    [ -n "$( pidof $sng )" ] && $S01sng_loc stop
+    [ -n "$( pidof $sng )" ] && $S01sng_init stop
     printf "\n$white starting system klogd and syslogd ... $green"
     service start_logger
-    if [ -e $syslogng_loc ]
+    if [ -e $sng_loc ]
     then
         sed -i "/$scribe_name/d" $srvc_event
-        dlt $S01sng_loc
+        dlt $S01sng_init
         dlt $rcfunc_loc
         dlt /tmp/syslog.log
         dlt /jffs/syslog.log
         dlt /jffs/syslog.log-1
         printf "\n$cyan"
         opkg remove "$sng"
-        dlt $syslogng_d
-        dlt $syslogng_share
-        dlt $syslogng_conf
+        dlt $sngd_d
+        dlt $sng_share
+        dlt $sng_conf
         dlt /tmp/syslog.log
         dlt /tmp/syslog.log-1
         if $skynet_inst; then sh $script_d/firewall settings syslog /tmp/syslog.log > /dev/null 2>&1; fi
@@ -538,15 +538,15 @@ uninstall(){
         not_installed "$sng"
     fi
 
-    if [ -e $logrotate_loc ]
+    if [ -e $lr_loc ]
     then
         sed -i "/cru a $lr/d" $postmount
         if cru l | grep -q $lr; then cru d $lr; fi
         printf "\n$cyan"
         opkg remove "$lr"
-        dlt $logrotate_d
-        dlt $logrotate_share
-        dlt $logrotate_conf
+        dlt $lrd_d
+        dlt $lr_share
+        dlt $lr_conf
         dlt $lr_daily
     else
         not_installed "$lr"
@@ -571,8 +571,8 @@ menu_uninstall(){
     printf "                *********************\n\n"
     printf "    This will remove the $yellow $sng $white and $yellow $lr $white packages!!\n"
     printf "    Ensure you have backed up any configuration files you wish\n"
-    printf "    to keep.  All configuration files in $yellow $syslogng_d $white \n"
-    printf "    and $yellow $logrotate_d $white will be deleted!\n\n"
+    printf "    to keep.  All configuration files in $yellow $sngd_d $white \n"
+    printf "    and $yellow $lrd_d $white will be deleted!\n\n"
     printf "                *********************\n"
     printf "                ***$red W*A*R*N*I*N*G$white ***\n"
     printf "                *********************\n\n"
@@ -680,7 +680,7 @@ gather_debug(){
     printf "\n### syslog-ng syntax check:\n" >> $scribe_debug
     if syslog-ng -s > /dev/null 2>&1
     then
-	    $syslogng_loc --preprocess-into=$sngconf_merged > /dev/null 2>&1
+	    $sng_loc --preprocess-into=$sngconf_merged > /dev/null 2>&1
         {
             printf "syslog-ng syntax check okay!\n"
             printf "\n### syslog-ng config:\n"
